version: "3.7"

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "psql -U user -d db -c 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_postgres_data:/var/lib/postgresql/data

  # api-gateway:
  #   container_name: api-gateway
  #   build:
  #     context: ../services/api-gateway
  #     dockerfile: ApiGateway.Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     db:
  #       condition: service_healthy

  # well-data-svc:
  #   container_name: well-data-svc
  #   build:
  #     context: ../services/well-data-svc
  #     dockerfile: WellDataSvc.Dockerfile
  #   ports:
  #     - 7000:7000
  #   depends_on:
  #     db:
  #       condition: service_healthy

volumes:
  db_postgres_data: