import SelectWithAdd from "./components/SelectWithAdd/SelectWithAdd";

const data = [
    {
        id: 'WellHeadPressure',
        text: 'Давление на устье скважины',
        measure: 'бар',
        min: 1,
        max: 20,
    },
    {
        id:'Depth',
        text: 'Глубина скважины',
        measure: 'м',
        min: 1000,
        max: 3000,
    },
    {
        id:'FluidCompressibility',
        text: 'Cжимаемость флюида (воды)',
        measure: '1/Па (e-9)',
        min: 4,
        max: 6,
    },
    {
        id:'FluidDensity',
        text: 'Плотность флюида',
        measure: 'кг/м3',
        min: 700,
        max: 1000,
    },
    {
        id:'PipeDiameter',
        text: 'Диаметр трубы',
        measure: 'м',
        min: 0.09,
        max: 0.2,
    },
    {
        id:'InclinationAngle',
        text: 'Угол наклона скважины к горизонту',
        measure: 'градусы',
        min: 0,
        max: 90,
    },
    {
        id:'SectionsNumber',
        text: 'Участков скважины',
        measure: 'ед',
        min: 1,
        max: 1000,
    },
    {
        id:'MoodyCoefficient',
        text: 'Коэффициент трения Муди',
        measure: '',
        min: 0.1,
        max: 0.9,
    },
    {
        id:'StartLiquidRate',
        text: 'Начальный дебит жидкости',
        measure: 'м3/сут',
        min: 0,
        max: 100,
    },
    {
        id:'Permeability',
        text: 'Проницаемость пласта',
        measure: 'мД',
        min: 1,
        max: 100,
    },
    {
        id:'Thickness',
        text: 'Толщина пласта',
        measure: 'м',
        min: 0.1,
        max: 100,
    },
    {
        id:'FluidViscosity',
        text: 'Вязкость флюида',
        measure: 'сП',
        min: 0.1,
        max: 100,
    },
    {
        id:'FluidVoumeFactor',
        text: 'Объемный коэффициент флюида',
        measure: '',
        min: 1,
        max: 2.1,
    },
    {
        id:'SaturationPressure',
        text: 'Давление насыщения',
        measure: 'бар',
        min: 1,
        max: 100,
    },
    {
        id:'AverageReservoirePressure',
        text: 'Среднее пластовое давление',
        measure: 'бар',
        min: 100,
        max: 300,
    },
    {
        id:'SupplyContourRadius',
        text: 'Радиус контура питания скважины',
        measure: 'м',
        min: 100,
        max: 1000,
    },
    {
        id:'WellRadius',
        text: 'Радиус скважины',
        measure: 'м',
        min: 0.05,
        max: 0.3,
    },
    {
        id:'SkinFactor',
        text: 'Скин-фактор скважины',
        measure: '',
        min: -3,
        max: 10,
    },
];

export default data;